---
- name: Deploy custom index page
  hosts: web_servers
  become: yes
  vars:
    web_root: /var/www/html/index.html
  tasks:
    - name: Deploy templated index page
      template:
        src: index.html.j2
        dest: "{{ web_root }}"
        owner: www-data
        group: www-data
        mode: '0644'
      notify: Restart nginx

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
